Simulation = "SimulationCarService"
Servers = 2
Bf = 4
Rounds = 1
RunWait = "6000s"
Suite = "Ed25519"
# Keep the different columns in case someboday wants to run another battery
# of tests

Keep,   Transactions, BatchSize,  Hosts,  Delay, BlockInterval
true,   10,           5,          5,      10,    "5s"
true,   20,           5,          5,      10,    "5s"
#true,   50,           5,          5,      10,    "5s"
#true,   100,          5,          5,      10,    "5s"
#true,   300,          5,          5,      10,    "5s"
#true,   500,          5,          5,      10,    "5s"
#true,   700,          5,          5,      10,    "5s"
#true,   1000,         5,          5,      10,    "5s"
#true,   10000,        5,          10,     10,    "5s"
#true,   100000,       5,          10,     10,    "5s"

#the number od hosts differs, what about the txns???
#true,   10,           5,          2,      10,    "5s"
#true,   50,           5,          5,      10,    "5s"
#true,   100,          5,          10,      10,    "5s"
#true,   300,          5,          50,      10,    "5s"
#true,   500,          5,          100,      10,    "5s"
#true,   700,          5,          1000,      10,    "5s"


